### ISSUE TITLE
issue https://github.com/cypress-io/cypress/issues/4925

### ISSUE THREAD

**Issue by miukki** [ManasPecenek/clinco#8]
Hi Manas!
not sure how to contact you, sorry for offtop..

issue https://github.com/cypress-io/cypress/issues/4925
when I run in osx 
```
mkdir -p /var/run/dbus && dbus-daemon --config-file=/usr/share/dbus-1/system.conf --print-address

```
got error 
```
dbus[14375]: Failed to start message bus: Failed to open "/usr/share/dbus-1/system.conf": No such file or directory
```
are you able to assist?

**Comment by ManasPecenek** [comment]
can you run `find /usr -name dbus-1`

**Comment by ManasPecenek** [comment]
Could you please try running `dbus-daemon --config-file=/opt/homebrew/share/dbus-1/system.conf --print-address`
